name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi, I am ${{ github.actor }}, working in ${{ github.repository}}"

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs
      - name: Deploy to GitHub Pagess
        id: deployment
        uses: actions/deploy-pages@v4